'use strict';

/**
 * The install document (`gi_system_states`, `_id: 'install'`): the setup lock and the owner pointer.
 *
 * Every write here is a single-document compare-and-set — the only lock primitive this build has
 * (no transactions on a standalone Mongo, spec I10). The lock is taken ONCE (`lockSetup`, filter
 * `setup_completed_at: null`) and never cleared by application code; the pointer moves only by CAS
 * on its current value (`moveOwnerPointer`).
 *
 * Reads no clock and no config: `now` and every value written are arguments.
 */

import models = require('../../shared/repositories/models.repository');
import authVocab = require('../../../constants/authVocab.constants');
import identityHelper = require('../helpers/identity.helper');

import type { ObjectIdLike, SystemStateDoc } from '../../shared/types/entity.types';

const { SystemStateModel } = models;
const { INSTALL_STATE_ID } = authVocab;

/**
 * Reads the install document.
 *
 * @returns The document, or `null` when boot has not created it (or it was deleted).
 */
const findInstallState = async (): Promise<SystemStateDoc | null> => {
    const doc = await SystemStateModel.findById(INSTALL_STATE_ID).lean<SystemStateDoc | null>();
    // Belt and braces (spec I8): the key the caller asked for is the key it gets.
    if (!doc || doc._id !== INSTALL_STATE_ID) {
        return null;
    }
    return doc;
};

/**
 * Creates the install document if it does not exist; never modifies an existing one.
 *
 * `$setOnInsert` only, so a second boot (or a concurrent one) leaves the stored lock and pointer
 * untouched. The service decides whether a new document starts OPEN (`locked_at: null`, only when
 * gi_users is empty) or LOCKED with no owner (spec A7) — this function writes what it is told.
 *
 * ⚠️ Two processes upserting at once can both miss and both insert; the loser throws E11000 on
 * `_id`. That error propagates — the service catches it and retries once (the retry then matches
 * the winner's document and inserts nothing).
 *
 * @param params0 - The parameters object.
 * @param params0.locked_at - `null` to create setup OPEN; an instant to create it LOCKED (no owner).
 * @returns `{ inserted }` — whether this call created the document.
 */
const ensureInstallDocument = async ({ locked_at }: { locked_at: Date | null }): Promise<{ inserted: boolean }> => {
    const result = await SystemStateModel.updateOne(
        { _id: INSTALL_STATE_ID },
        {
            $setOnInsert: {
                setup_completed_at: locked_at,
                owner_user_id: null,
                setup_token_id: null
            }
        },
        { upsert: true }
    );
    return { inserted: (result.upsertedCount || 0) > 0 };
};

/**
 *  THE SETUP LOCK. Compare-and-set on `setup_completed_at: null` — exactly one caller can win.
 *
 * Two concurrent setup completions both reach this line; the server serialises them, the first
 * flips the flag and gets the document back, the second matches nothing and gets `null`. There is
 * no separate check to race against.
 *
 * @param params0 - The parameters object.
 * @param params0.owner_user_id - The id the owner row WILL be inserted with (pre-generated by the service).
 * @param params0.setup_token_id - The SETUP_VERIFY token whose claim carries the owner's name + hash.
 * @param params0.now - Recorded as `setup_completed_at`.
 * @returns The locked document, or `null` when setup was already locked (or the document is absent —
 *     the service re-reads to tell those two apart).
 */
const lockSetup = async ({ owner_user_id, setup_token_id, now }: {
    owner_user_id: ObjectIdLike;
    setup_token_id: ObjectIdLike;
    now: Date;
}): Promise<SystemStateDoc | null> => {
    if (!identityHelper.isObjectIdLike(owner_user_id) || !identityHelper.isObjectIdLike(setup_token_id)) {
        return null;
    }
    const doc = await SystemStateModel.findOneAndUpdate(
        { _id: INSTALL_STATE_ID, setup_completed_at: null },
        {
            $set: {
                setup_completed_at: now,
                owner_user_id: owner_user_id,
                setup_token_id: setup_token_id
            }
        },
        { returnDocument: 'after' }
    ).lean<SystemStateDoc | null>();
    if (!doc || doc._id !== INSTALL_STATE_ID) {
        return null;
    }
    return doc;
};

/**
 * Moves the owner pointer, by CAS on its CURRENT value (CLI `transfer-owner` and `repair-owner`).
 *
 * Only on a LOCKED install: an open install has no owner to move, and setting a pointer there would
 * not close setup. `from_owner_user_id: null` matches a null or missing pointer (spec A17:
 * `transfer-owner` accepts a null or dangling pointer — a dangling one is passed as its value).
 *
 * @param params0 - The parameters object.
 * @param params0.from_owner_user_id - The pointer value the caller read, or `null`.
 * @param params0.to_owner_user_id - The new owner's `gi_users._id`.
 * @returns The updated document, or `null` when the pointer changed since it was read (or setup is open).
 */
const moveOwnerPointer = async ({ from_owner_user_id, to_owner_user_id }: {
    from_owner_user_id: ObjectIdLike | null;
    to_owner_user_id: ObjectIdLike;
}): Promise<SystemStateDoc | null> => {
    if (!identityHelper.isObjectIdLike(to_owner_user_id)) {
        return null;
    }
    if (from_owner_user_id !== null && !identityHelper.isObjectIdLike(from_owner_user_id)) {
        return null;
    }
    const doc = await SystemStateModel.findOneAndUpdate(
        {
            _id: INSTALL_STATE_ID,
            setup_completed_at: { $ne: null },
            owner_user_id: from_owner_user_id
        },
        { $set: { owner_user_id: to_owner_user_id } },
        { returnDocument: 'after' }
    ).lean<SystemStateDoc | null>();
    if (!doc || doc._id !== INSTALL_STATE_ID) {
        return null;
    }
    return doc;
};

export = {
    findInstallState,
    ensureInstallDocument,
    lockSetup,
    moveOwnerPointer
};
